#+ summary: Elements and their isotopes
#+ description: Elements and their isotopes
#+ endpoint: https://query.wikidata.org/bigdata/namespace/wdq/sparql
#+ pagination: 100
#+ method: GET
#+ tags:
#+   - Isotopes

PREFIX wdt: <http://www.wikidata.org/prop/direct/>
#title: Elements and their isotopes.
SELECT DISTINCT ?element ?element_symbol ?isotope ?isotope_mass ?isotope_abundance WHERE {
  ?isotope wdt:P2374 ?isotope_abundance;
    wdt:P2067 ?isotope_mass;
    wdt:P279 ?element.
  ?element wdt:P246 ?element_symbol.
}
ORDER BY (?isotope_mass)
