#+ summary: Which structures are isotopically-labeled ones?
#+ description: Which structures are isotopically-labeled ones?
#+ endpoint: https://query.wikidata.org/bigdata/namespace/wdq/sparql
#+ pagination: 100
#+ method: GET
#+ tags:
#+   - Isotopes

PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX hint: <http://www.bigdata.com/queryHints#>
#title: Which structures are isotopically-labeled ones?
SELECT ?structure WHERE {
    ?structure wdt:P234 ?inchi. hint:Prior hint:rangeSafe TRUE.
    FILTER(REGEX(STR(?inchi), "/i"))
}
